### ISSUE TITLE
提一个建议

### ISSUE THREAD

**Issue by farawayliu** [r12f/hexo-heading-index#3]
当文章标题以###开始，而非#开始时，会出现：0.0.1的标题。

这应该是不合适的。期望的结果时，以最少的#的标题开始计算。例如
###
  ####
  ####

出现的结果期望是：
1. 
  1.1   
  1.2

**Comment by farawayliu** [comment]
> 当文章标题以###开始，而非#开始时，会出现：0.0.1的标题。
> 
> 这应该是不合适的。期望的结果时，以最少的#的标题开始计算。例如
> 
> 出现的结果期望是：
> 1.
> 1.1
> 1.2

因为我使用的hexo主题，#的样式字体太大，我一般从###开始

**Comment by r12f** [comment]
我添加了一个`start_level`的支持，希望能满足你的需求～

**Comment by r12f** [comment]
Commit: 3bb349d13eafde7bd7024b6ae417619ebe42856e
