### ISSUE TITLE
为单独的 post 设置是否使用 heading index

### ISSUE THREAD

**Issue by zhongfq** [r12f/hexo-heading-index#4]
是否可以为单独的 post 添加 heading_enabled属性，默认可以 true。这样一来，有些 post 可以不自动添加 heading index

**Comment by r12f** [comment]
没问题，已经提交并且发布啦：1.0.3。

- link: https://www.npmjs.com/package/hexo-heading-index/v/1.0.3
- commit：0c07ef0fea9a585ce13fc3be648daf5ee2daed71

**Comment by zhongfq** [comment]
nice!!
